### ISSUE TITLE
It's strongly recommended that you re-arrange the structure of your project

### ISSUE THREAD

**Issue by PaperCube** [visualDust/MockFormula#1]
Your project contains too much file which are unused, and too much files that shouldn't be involved in version control system, e.g. logs, build cache and so on. Please consider simplify them and ignore some unnecessary files

**Comment by visualDust** [comment]
We are both Chinese . Why use English ?

**Comment by PaperCube** [comment]
It's a good manner to talk in English on this international site

**Comment by visualDust** [comment]
International site is true . But with a project for Chinese .

**Comment by visualDust** [comment]
你什么时候把新的README.MD 给 PULL REQUEST?

**Comment by 134ARG** [comment]
(manual 'funny)

**Comment by visualDust** [comment]
Zhou ....
